permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: lionel shen
  #email
  link: http://lionelshen.cn
  weibo: http://weibo.com/wolflion
  github: http://github.com/wolflion
  #music
  douban: https://www.douban.com/people/wolflion/
  #linkedin: https://www.linkedin.com/pub/anya-lin/81/91/232
  zhihu: https://www.zhihu.com/people/wolflion
  
 # 百度统计
 # baidu-analysis：https://hm.baidu.com/hm.js?463077977207b46b4d9bd9e8c40bbb6f

# 站点信息
title: 天行的博客
description: My personal blog
url: http://lionelshen.cn
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/lionel.png
favicon: /public/img/lionel.png

# google analytics 设置
ga:
#  id: UA-54262064-1 
   id: UA-97408177-1
   url: lionelshen.cn

# disqus 设置
disqus:
  shortname: lionelshen

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - 通用
  - Tool

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档